version: '3.5'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      ELASTICSEARCH_HOSTS: http://im-tf-ecs-alb-elasticsearcn-970a1b2aee386214.elb.ap-southeast-1.amazonaws.com:9200/
    ports:
      - "0.0.0.0:5601:5601"