version: '3.5'

services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sam_wang@ctl.creative.com
      PGADMIN_DEFAULT_PASSWORD: 100200
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "0.0.0.0:5050:80"
    restart: unless-stopped

volumes:
    pgadmin: